### ISSUE TITLE
웹페이지 배포

### ISSUE THREAD

**Issue by Zimins** [Debaters/DebateOnWeb#9]
작업중인 페이지를 현재 배포된 아마존 서버에서 조회 할 수 있도록 작업

**Comment by otw7917** [comment]
09/24 금요일 

## 작업중
- Github Registry 에 npm package로 배포(publish) 단계
- Github Actions을 통해 publish 하기 

## 계획중
- aws lightsail access key 팀단위 공유가 가능한지 방법 찾아보기 IAM? 


## 의문점
- yarn build시 오류 발생 
- private 
- 정적파일 html, js 같은 경우 s3 많이 쓴다고 함, 왜?
